#
#
#
version: '3.9'
services:
  dev:
    build: .
    cap_add:
      - SYS_ADMIN
    volumes:
    - .:/code
    entrypoint: /usr/bin/tail
    command:
    - -f
    - /etc/hosts
  scan:
    build: .
    cap_add:
      - SYS_ADMIN
    volumes:
    - .:/code
    command: [ "grype" ]
